name: Pruebas de Behat

on: [push, pull_request]

jobs:
  behat:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v2

    - name: Instalar PHP y Composer
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        tools: composer:v2

    - name: Instalar dependencias
      run: composer install --no-progress --no-suggest

    - name: Ejecutar pruebas con Behat
      run: vendor/bin/behat --format=junit --out=behat-reports/

    - name: Subir informes de Behat
      uses: actions/upload-artifact@v2
      with:
        name: behat-reports
        path: behat-reports/
