default:
  paths:
    features: features
  suites:
    default:
      paths: [ "%paths.base%/features" ]
      contexts:
        - FeatureContext
  formatters:
    html:
      output_path: report/behat.html
