name: Tarea Automatizada de ejecución de pruebas

env:
  SONAR_ORG: 'albert1'                  # Nombre de la organización en SonarCloud
  SONAR_PROJECT: 'albert1_sosa'         # Key ID del proyecto en SonarCloud

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build and Analyze
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'               # Ajusta la versión de PHP según tus necesidades
        extensions: mbstring, intl, pdo_mysql

    - name: Instalar dependencias de Composer
      run: |
        composer install --no-progress --prefer-dist

    - name: Crear directorio para reportes
      run: mkdir -p features/bootstrap/reports

    - name: Dar permisos de ejecución a Behat
      run: chmod +x vendor/bin/behat

    - name: Ejecutar pruebas con Behat
      run: vendor/bin/behat --format=html --out=features/bootstrap/reports/index.html

    - name: Escaneo en SonarCloud
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Necesario para obtener información de PR, si existe
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Subir informe HTML de Behat
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: behat-report
        path: features/bootstrap/reports/index.html

    - name: Desplegar informe HTML de Behat en GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.PAT_TOKEN }}
        publish_branch: bddreporte
        publish_dir: features/bootstrap/reports
