name: Tarea Automatizada de ejecuci贸n de pruebas

env:
  SONAR_ORG: 'sosa proyecto'                # Nombre de la organizaci贸n de SonarCloud
  SONAR_PROJECT: 'sosa-proyecto_sosau3'     # Key ID del proyecto en SonarCloud
  COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}   # Autenticaci贸n para Composer

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  coverage:
    name: Cobertura y SonarCloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout c贸digo
        uses: actions/checkout@v2

      - name: Instalar PHP y Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          tools: composer:v2

      - name: Instalar dependencias
        run: composer install --no-progress --no-suggest --prefer-dist

      - name: Ejecutar pruebas con Behat
        run: vendor/bin/behat --format=junit --out=behat-reports/

      - name: Instalar y configurar Xdebug
        run: echo "xdebug.mode=coverage" >> $PHP_INI_DIR/conf.d/xdebug.ini

      - name: Ejecutar pruebas con cobertura
        run: vendor/bin/behat --format=clover --out=behat-reports/clover.xml

      - name: Configurar SonarCloud
        run: |
          wget https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip
          unzip build-wrapper-linux-x86.zip
          export PATH=$PATH:$(pwd)/build-wrapper-linux-x86
          sonar-scanner -Dsonar.projectKey=$SONAR_PROJECT -Dsonar.organization=$SONAR_ORG -Dsonar.sources=. -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Subir informe de cobertura
        uses: actions/upload-artifact@v2
        with:
          name: cobertura
          path: behat-reports/clover.xml
